USE ADVANCEDSQL

SELECT * FROM EMPLOYEES;


--WITH OUT CURSOR VARIABLES

DECLARE C1 CURSOR SCROLL FOR SELECT * FROM EMPLOYEES
OPEN C1
FETCH LAST FROM C1
FETCH PRIOR FROM C1
FETCH ABSOLUTE 5 FROM C1
FETCH RELATIVE -2 FROM C1
FETCH RELATIVE 2 FROM C1
FETCH FIRST FROM C1
FETCH NEXT FROM C1
CLOSE C1
DEALLOCATE C1;


--WITH CURSOR VARIABLES

DECLARE C2 CURSOR SCROLL FOR SELECT EMPID,EMPNAME FROM EMPLOYEES
DECLARE @EMPID INT,@EMPNAME VARCHAR(20)
OPEN C2
FETCH LAST FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

FETCH PRIOR FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

FETCH ABSOLUTE 5 FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

FETCH RELATIVE -2 FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

FETCH RELATIVE 2 FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

FETCH FIRST FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

FETCH NEXT FROM C2 INTO @EMPID,@EMPNAME
PRINT 'THE EMPLOYE NAME '+@EMPNAME+' '+'  ID IS '+CAST(@EMPID AS VARCHAR(20))

CLOSE C2

DEALLOCATE C2;



SELECT * FROM CUSTOMER


-- Declare variables to store employee details
DECLARE @EMPID INT, @EMPNAME NVARCHAR(50), @EMPSALARY INT

-- Declare and define the cursor
DECLARE employee_cursor CURSOR FOR
SELECT EMPID,EMPNAME,EMPSALARY
FROM EMPLOYEES

-- Open the cursor
OPEN employee_cursor

-- Fetch the first row from the cursor
FETCH NEXT FROM employee_cursor INTO @EmpID, @EMPNAME, @EMPSALARY

-- Loop through the result set and print employee details
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'EMPID: ' + CAST(@EMPID AS VARCHAR(10)) + ', EmpName: ' + @EmpName + ', EmpSalary: ' +CAST( @EmpSalary AS VARCHAR(50))
    
    -- Fetch the next row
    FETCH NEXT FROM employee_cursor INTO @EMPID, @EMPName, @EMPSALARY
END

-- Close the cursor
CLOSE employee_cursor

-- Deallocate the cursor
DEALLOCATE employee_cursor












