USE ADVANCEDSQL;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;


CREATE VIEW V1 AS SELECT * FROM EMPLOYEES;

SELECT * FROM V1;

INSERT V1 VALUES(8,'RAM CHARAN',20000,'BANGLORE',2);

UPDATE V1 SET EMPNAME='NTR' WHERE EMPID=8;

DELETE FROM V1 WHERE EMPID=8;

CREATE VIEW VIEW3  AS SELECT EMPID,EMPNAME,EMPSALARY 
FROM EMPLOYEES 
WHERE EMPID>3;

SELECT * FROM VIEW3;


CREATE OR ALTER VIEW VIEW4 AS 
SELECT EMPID,EMPNAME,EMPSALARY,DEPTNAME,DEPTCITY 
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPTID=DEPARTMENTS.DEPTID;

SELECT * FROM VIEW4;

CREATE OR ALTER VIEW VIEW5 AS 
SELECT EMPID,EMPNAME,EMPSALARY,DEPTNAME,DEPTCITY 
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPTID=DEPARTMENTS.DEPTID AND EMPSALARY >300000;

SELECT * FROM VIEW5


CREATE OR ALTER VIEW VIEW6 AS 
SELECT EMPID,EMPNAME,EMPSALARY,DEPTNAME,DEPTCITY 
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPTID=DEPARTMENTS.DEPTID AND DEPTCITY='HYDERABAD';

SELECT * FROM VIEW6;


CREATE OR ALTER VIEW VIEW7 AS
SELECT EMPID,EMPNAME,EMPSALARY,DEPTNAME,DEPTCITY
FROM EMPLOYEES INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPTID =DEPARTMENTS.DEPTID AND DEPTCITY='HYDERABAD';


SELECT * FROM VIEW7;


--DROP
DROP VIEW VIEW7;

--RENAME
Sp_Rename VIEW7, VIEWW7;

SELECT * FROM VIEWW7;

--HELPTEXT
Sp_Helptext vieww7;


--REFRESHING A VIEW
CREATE VIEW VIEW8
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM VIEW8;

ALTER TABLE EMPLOYEES ADD  EMPPANNUMBER INT;

--REFRESH VIEW

EXEC sp_refreshview VIEW8;

SELECT * FROM VIEW8;


--SCHEMA BINDING

CREATE OR ALTER  VIEW VIEW9
WITH SCHEMABINDING
AS
SELECT EMPID,EMPNAME,EMPSALARY FROM dbo.EMPLOYEES;


SELECT * FROM VIEW9;

ALTER TABLE EMPLOYEES ADD EMPAADHAR INT;

EXEC SP_RENAME 'EMPLOYEES.EMPAADHAR','EMPAA';

ALTER TABLE EMPLOYEES  DROP COLUMN EMPAADHAR;

SELECT * FROM EMPLOYEES;

SELECT * FROM VIEW9;

SP_HELPTEXT VIEW9; 

--ENCRYPTION
CREATE OR ALTER  VIEW VIEW10
WITH ENCRYPTION
AS SELECT EMPID,EMPNAME,EMPSALARY FROM EMPLOYEES

SELECT * FROM VIEW10;

 SP_HELPTEXT VIEW10; 


 --CHECK

 CREATE OR ALTER  VIEW VIEW11
WITH ENCRYPTION
AS SELECT EMPID,EMPNAME,EMPSALARY 
FROM EMPLOYEES WHERE EMPSALARY>300000
WITH CHECK OPTION;

SELECT * FROM EMPLOYEES;

INSERT INTO VIEW11 VALUES(8,'SAHOO',234);

INSERT INTO VIEW11 VALUES(8,'SAHOO',800000);

SELECT *  FROM VIEW11;



SELECT * FROM EMPLOYEE;



SELECT * FROM EMPLOYEES;



